//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecomAdminPanel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Brands
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brands()
        {
            this.Products1 = new HashSet<Products1>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "Category field cannot be empty")]
        public int CategoryID { get; set; }
        [Required(ErrorMessage = "Brand field cannot be empty")]
        public string Brand { get; set; }
        [Required(ErrorMessage = "Explanation field cannot be empty")]
        [Display(Name ="Explanation")]
        public string Explanation { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products1> Products1 { get; set; }
    }
}
